BulkyBook/Areas/Admin/Controllers/CategoryController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitofwork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitofwork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Category category = new Category();
            if(id == null)
            {
                // This is for create
                return View(category);
            }
            // This is for Edit
            category = _unitofwork.category.Get(id.GetValueOrDefault());
            if(category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Category category)
        {
            if(ModelState.IsValid)
            {
                if(category.Id ==0)
                {
                    _unitofwork.category.Add(category);
                    
                }
                else
                {
                    _unitofwork.category.Update(category);
                }
                _unitofwork.Save();
                return RedirectToAction(nameof(Index));
            }
                return View(category);
            
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitofwork.category.GetAll();
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objfromDb = _unitofwork.category.Get(id);
            if(objfromDb == null)
            {
                return Json(new { success = false, message = "Error in Deleting" });
            }
            _unitofwork.category.Remove(objfromDb);
            _unitofwork.Save();
            return Json(new { success = true, message = " Delete Successful" });
        }
    }
}

BulkyBook/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitofwork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitofwork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Company company = new Company();
            if(id == null)
            {
                // This is for create
                return View(company);
            }
            // This is for Edit
            company = _unitofwork.company.Get(id.GetValueOrDefault());
            if(company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company  company)
        {
            if(ModelState.IsValid)
            {
                if(company.Id ==0)
                {
                    _unitofwork.company.Add(company);
                    
                }
                else
                {
                    _unitofwork.company.Update(company);
                }
                _unitofwork.Save();
                return RedirectToAction(nameof(Index));
            }
                return View(company);
            
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitofwork.company.GetAll();
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objfromDb = _unitofwork.company.Get(id);
            if(objfromDb == null)
            {
                return Json(new { success = false, message = "Error in Deleting" });
            }
            _unitofwork.company.Remove(objfromDb);
            _unitofwork.Save();
            return Json(new { success = true, message = " Delete Successful" });
        }
    }
}

BulkyBook/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitofwork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitofwork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            ProductViewModel vm = new ProductViewModel()
            {
                product = new Product(),
                CategoryList = _unitofwork.category.GetAll().Select(i => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                CoverTypeList = _unitofwork.coverType.GetAll().Select(i => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = i.NAME,
                    Value = i.ID.ToString()
                })
            };
            if(id == null)
            {
                // This is for create
                return View(vm);
            }
            // This is for Edit
           vm.product = _unitofwork.product.Get(id.GetValueOrDefault());
            if(vm.product == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductViewModel productViewModel)
        {
            if(ModelState.IsValid)
            {
                string webRootPath = _hostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    string filename = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(webRootPath, @"Images\Products");
                    var extension = Path.GetExtension(files[0].FileName);
                    if(productViewModel.product.Imageurl != null)
                    {
                        // This is for edit & we need to remove an old image
                        var imagepath = Path.Combine(webRootPath, productViewModel.product.Imageurl.TrimStart('\\'));
                        if (System.IO.File.Exists(imagepath))
                        {
                            System.IO.File.Delete(imagepath);
                        }
                    }
                    using(var filestreams = new FileStream(Path.Combine(uploads,filename+extension),FileMode.Create))
                    {
                        files[0].CopyTo(filestreams);
                    }
                    productViewModel.product.Imageurl = @"\Images\Products\\" + filename + extension;
                }
                else
                {
                    // Update when they do not change the image
                    if(productViewModel.product.Id != 0)
                    {
                        Product objfromdb = _unitofwork.product.Get(productViewModel.product.Id);
                        productViewModel.product.Imageurl = objfromdb.Imageurl;
                    }
                }
                if(productViewModel.product.Id == 0)
                {
                    _unitofwork.product.Add(productViewModel.product);
                }
                else
                {
                    _unitofwork.product.Update(productViewModel.product);
                }
                _unitofwork.Save();
                return RedirectToAction("Index");
            }
            else
            {
               productViewModel.CategoryList = _unitofwork.category.GetAll().Select(i => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
               productViewModel.CoverTypeList = _unitofwork.coverType.GetAll().Select(i => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
                {
                    Text = i.NAME,
                    Value = i.ID.ToString()
                });
                
                if(productViewModel.product.Id != 0)
                {
                    productViewModel.product = _unitofwork.product.Get(productViewModel.product.Id);
                }
            }
               return View(productViewModel);
            
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitofwork.product.GetAll(includeProperties:("Category,CoverType"));
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {

            var objfromDb = _unitofwork.product.Get(id);
            if(objfromDb == null)
            {
                return Json(new { success = false, message = "Error in Deleting" });
            }
            string webRootPath = _hostEnvironment.WebRootPath;
            var imagepath = Path.Combine(webRootPath, objfromDb.Imageurl.TrimStart('\\'));
            if (System.IO.File.Exists(imagepath))
            {
                System.IO.File.Delete(imagepath);
            }
            _unitofwork.product.Remove(objfromDb);
            _unitofwork.Save();
            return Json(new { success = true, message = " Delete Successful" });
        }
    }
}

BulkyBook/Areas/Admin/Controllers/UserController.cs
using BulkyBook.DataAccess.Data;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BulkyBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        

        [HttpGet]
        public IActionResult GetAll()
        {
            var userList = _db.applicationUsers.Include(u => u.company).ToList();
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            foreach(var user in userList )
            {
                var roleId = userRole.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
                if(user.Name== null)
                {
                    user.company = new Company();
                    {
                        user.Name = "";
                    };

                }
            }
            return Json(new { data = userList });
        }

        
    }
}

BulkyBook/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>

</div>

BulkyBook/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary" asp-route-id="@Model">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>

</div>

BulkyBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                ContentManagment
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                                <a class="dropdown-item" href="#">Add More</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                User / Company
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                            </div>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-white-50 bg-primary">
        <div class="container">
            &copy; 2021 - BulkyBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/f95eaae757.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>